name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            echo "Connected to server successfully"

            mkdir -p ~/app
            cd ~/app

            echo "Downloading docker-compose.yml..."

            curl -fsSL -o docker-compose.yml \
              https://raw.githubusercontent.com/Ayomide9ja/formflow-capstone/main/docker-compose.yml

            echo "Creating .env file..."

            echo "APP_VERSION=${{ github.sha }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            echo "Checking Docker..."

            docker --version

            echo "Checking Docker Compose..."

            docker compose version

            echo "Pulling latest images..."

            docker compose pull

            echo "Starting containers..."

            docker compose up -d --remove-orphans

            echo "Deployment completed successfully"